def draw_museum():
    print("             ^       ")
    print("            / \       ")
    print("           /   \       ")
    print("          /     \     ")
    print("         /       \     ")
    print("        /         \    ")
    print("       /           \   ")
    print("      /             \  ")
    print(" --------------------------- ")
    print(" |          MUSEUM         | ")
    print(" --------------------------- ")
    print("  (  )      (  )       ( )   ")
    print("  |  |      |  |       | |  ")
    print("  |  |      |  |       | |  ")
    print("  |  |      |  |       | |  ")
    print("  |  |      |  |       | |  ")
    print("  |  |      |  |       | |  ")
    print(" ____________________________")
    print("/____________________________\ ")

    #print("museum not found")
    return